dist: xenial
group: edge
language: python
os: linux
services:
  - docker

jobs:
  include:
    - env: DIST=centos-8
    - env: DIST=fedora-30
    - env: DIST=fedora-31
    - env: DIST=fedora-32

before_install:
  - docker pull quay.io/ovirt/imageio-test-$DIST
  - docker run -it --rm quay.io/ovirt/imageio-test-$DIST ip -6 addr

script:
  - |
    docker run \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/src:Z \
    quay.io/ovirt/imageio-test-$DIST \
    bash -c "cd /src && travis/test.sh"
