dist: xenial
group: edge
language: python
os: linux
services:
  - docker

jobs:
  include:
    - env: DIST=centos-8
    - env: DIST=fedora-30
    - env: DIST=fedora-31
    - env: DIST=fedora-32

before_install:
  - docker pull quay.io/ovirt/imageio-test-$DIST
  - |
    docker run \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/src:Z \
    quay.io/ovirt/imageio-test-$DIST \
    bash -c "cd /daemon && python3 -c 'from test.testutil import ipv6_supported; ipv6_supported(use_stdout=True)'"

script:
  - |
    docker run \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/src:Z \
    quay.io/ovirt/imageio-test-$DIST \
    bash -c "cd /src && travis/test.sh"
